"use client";
import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { TrendingUp, Eye, Users, Store, CalendarDays, Mail, Smartphone, Monitor, Tablet } from "lucide-react";
import { AreaChart, Area, BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, CartesianGrid } from "recharts";
import { cn } from "@/lib/utils";
const PIE_COLORS = ["oklch(0.64 0.215 32)", "oklch(0.78 0.16 78)", "oklch(0.55 0.13 162)"];
function fmtDate(s: string) { const d = new Date(s); return d.toLocaleDateString("es-BO", { weekday: "short", day: "2-digit" }); }
export function AnalyticsPanel() {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { let c = false; (async () => { try { const res = await fetch("/api/admin/analytics", { cache: "no-store" }); const d = await res.json(); if (!c && d?.ok) setData(d.analytics); } catch {} finally { if (!c) setLoading(false); } })(); return () => { c = true; }; }, []);
  if (loading) return <div className="grid place-items-center py-20"><div className="h-8 w-8 rounded-full border-2 border-primary border-t-transparent animate-spin" /></div>;
  if (!data) return <div className="text-center py-12 text-muted-foreground">No hay datos disponibles.</div>;
  const deviceData = [{ name: "Móvil", value: data.deviceBreakdown.mobile, icon: Smartphone }, { name: "Desktop", value: data.deviceBreakdown.desktop, icon: Monitor }, { name: "Tablet", value: data.deviceBreakdown.tablet, icon: Tablet }].filter((d) => d.value > 0);
  const statCards = [
    { label: "Visitas totales", value: data.totalViews, sub: `${data.viewsLast7d} últimos 7 días`, icon: Eye, color: "text-primary", bg: "bg-primary/10" },
    { label: "Suscriptores", value: data.subscribersTotal, sub: `+${data.subscribersLast7d} esta semana`, icon: Users, color: "text-emerald", bg: "bg-emerald/12" },
    { label: "Tiendas activas", value: data.contentStats.stores, sub: "en el directorio", icon: Store, color: "text-[#7a4d00]", bg: "bg-gold/15" },
    { label: "Eventos próximos", value: data.contentStats.upcomingEvents, sub: `${data.contentStats.events} total`, icon: CalendarDays, color: "text-ink", bg: "bg-ink/8" },
  ];
  return (
    <div className="space-y-6">
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{statCards.map((s, i) => { const Icon = s.icon; return (<motion.div key={s.label} initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.06 }} className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between mb-3"><span className={cn("grid place-items-center h-10 w-10 rounded-xl", s.bg)}><Icon className={cn("h-5 w-5", s.color)} /></span><TrendingUp className="h-4 w-4 text-emerald" /></div><div className="font-display font-extrabold text-3xl text-ink">{s.value.toLocaleString("es-BO")}</div><div className="text-xs text-muted-foreground mt-0.5">{s.label}</div><div className="text-[0.7rem] text-emerald font-medium mt-1">{s.sub}</div></motion.div>); })}</div>
      <div className="grid lg:grid-cols-3 gap-4">
        <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="lg:col-span-2 rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between mb-4"><div><h3 className="font-display font-bold text-ink">Visitas de los últimos 7 días</h3><p className="text-xs text-muted-foreground">Tráfico del sitio por día</p></div><Eye className="h-5 w-5 text-primary" /></div><ResponsiveContainer width="100%" height={220}><AreaChart data={data.viewsByDay}><defs><linearGradient id="viewsGrad" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="oklch(0.64 0.215 32)" stopOpacity={0.4} /><stop offset="100%" stopColor="oklch(0.64 0.215 32)" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="oklch(0.9 0.015 70)" vertical={false} /><XAxis dataKey="date" tickFormatter={fmtDate} tick={{ fontSize: 11, fill: "oklch(0.48 0.02 55)" }} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 11, fill: "oklch(0.48 0.02 55)" }} axisLine={false} tickLine={false} allowDecimals={false} /><Tooltip contentStyle={{ borderRadius: 12, border: "1px solid oklch(0.9 0.015 70)", fontSize: 12 }} labelFormatter={(l) => fmtDate(l as string)} /><Area type="monotone" dataKey="views" stroke="oklch(0.64 0.215 32)" strokeWidth={2.5} fill="url(#viewsGrad)" /></AreaChart></ResponsiveContainer></motion.div>
        <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="rounded-2xl border border-border bg-card p-5"><h3 className="font-display font-bold text-ink mb-1">Dispositivos</h3><p className="text-xs text-muted-foreground mb-3">Últimos 7 días</p>{deviceData.length > 0 ? (<><ResponsiveContainer width="100%" height={140}><PieChart><Pie data={deviceData} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius={35} outerRadius={55} paddingAngle={3}>{deviceData.map((_, i) => <Cell key={i} fill={PIE_COLORS[i % PIE_COLORS.length]} />)}</Pie><Tooltip contentStyle={{ borderRadius: 12, fontSize: 12 }} /></PieChart></ResponsiveContainer><div className="space-y-1.5 mt-2">{deviceData.map((d, i) => { const Icon = d.icon; const total = deviceData.reduce((a, b) => a + b.value, 0); const pct = total > 0 ? Math.round((d.value / total) * 100) : 0; return (<div key={d.name} className="flex items-center gap-2 text-xs"><Icon className="h-3.5 w-3.5 text-muted-foreground" /><span className="flex-1 text-muted-foreground">{d.name}</span><span className="font-semibold text-ink">{pct}%</span></div>); })}</div></>) : <div className="grid place-items-center h-32 text-xs text-muted-foreground">Sin datos aún</div>}</motion.div>
      </div>
      <div className="grid lg:grid-cols-2 gap-4">
        <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }} className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between mb-4"><div><h3 className="font-display font-bold text-ink">Crecimiento de suscriptores</h3><p className="text-xs text-muted-foreground">Últimos 30 días (acumulado)</p></div><Users className="h-5 w-5 text-emerald" /></div><ResponsiveContainer width="100%" height={180}><AreaChart data={data.subscriberGrowth}><defs><linearGradient id="subGrad" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="oklch(0.55 0.13 162)" stopOpacity={0.4} /><stop offset="100%" stopColor="oklch(0.55 0.13 162)" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="oklch(0.9 0.015 70)" vertical={false} /><XAxis dataKey="date" tick={{ fontSize: 10, fill: "oklch(0.48 0.02 55)" }} axisLine={false} tickLine={false} interval={6} /><YAxis tick={{ fontSize: 11, fill: "oklch(0.48 0.02 55)" }} axisLine={false} tickLine={false} allowDecimals={false} /><Tooltip contentStyle={{ borderRadius: 12, fontSize: 12 }} /><Area type="monotone" dataKey="total" stroke="oklch(0.55 0.13 162)" strokeWidth={2.5} fill="url(#subGrad)" /></AreaChart></ResponsiveContainer></motion.div>
        <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.5 }} className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between mb-4"><div><h3 className="font-display font-bold text-ink">Páginas más visitadas</h3><p className="text-xs text-muted-foreground">Todo el tiempo</p></div></div><div className="space-y-2.5 max-h-[180px] overflow-y-auto scroll-fancy">{data.topPages.length > 0 ? data.topPages.map((p: any, i: number) => (<div key={p.path} className="flex items-center gap-3"><span className="grid place-items-center h-7 w-7 rounded-lg bg-muted text-xs font-bold text-muted-foreground shrink-0">{i + 1}</span><span className="flex-1 text-sm font-medium text-ink truncate">{p.path}</span><span className="text-sm font-bold text-primary">{p.views}</span></div>)) : <div className="text-center py-8 text-xs text-muted-foreground">Sin datos aún</div>}</div></motion.div>
      </div>
    </div>
  );
}
