"use client";
import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Mail, Trash2, RefreshCw, MailOpen, Archive, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";
const statusConfig: Record<string, { label: string; color: string }> = { new: { label: "Nuevo", color: "bg-primary/10 text-primary" }, read: { label: "Leído", color: "bg-muted text-muted-foreground" }, replied: { label: "Respondido", color: "bg-emerald/12 text-emerald" }, archived: { label: "Archivado", color: "bg-muted text-muted-foreground" } };
export function MessagesPanel() {
  const [items, setItems] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<any | null>(null);
  const { toast } = useToast();
  const load = async () => { setLoading(true); try { const res = await fetch("/api/admin/messages", { cache: "no-store" }); const data = await res.json(); if (data?.ok) setItems(data.items); } catch {} finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const updateStatus = async (id: string, status: string) => { try { await fetch(`/api/admin/messages/${id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); load(); if (selected?.id === id) setSelected((s) => s ? { ...s, status } : null); } catch {} };
  const remove = async (id: string) => { if (!confirm("¿Eliminar este mensaje?")) return; try { await fetch(`/api/admin/messages/${id}`, { method: "DELETE" }); toast({ title: "Eliminado" }); if (selected?.id === id) setSelected(null); load(); } catch {} };
  const openMsg = (m: any) => { setSelected(m); if (m.status === "new") updateStatus(m.id, "read"); };
  const newCount = items.filter((m) => m.status === "new").length;
  return (
    <div>
      <div className="flex items-center justify-between gap-3 mb-4"><div className="text-sm text-muted-foreground"><span className="font-bold text-ink">{items.length}</span> mensajes · <span className="font-bold text-primary">{newCount}</span> nuevos</div><Button variant="ghost" size="icon" onClick={load} className="h-9 w-9"><RefreshCw className={cn("h-4 w-4", loading && "animate-spin")} /></Button></div>
      {loading ? <div className="grid place-items-center py-12"><div className="h-8 w-8 rounded-full border-2 border-primary border-t-transparent animate-spin" /></div> : items.length === 0 ? <div className="text-center py-12"><Mail className="mx-auto h-10 w-10 text-muted-foreground/40 mb-2" /><p className="text-sm text-muted-foreground">No hay mensajes todavía.</p></div> : (
        <div className="space-y-1.5 max-h-[60vh] overflow-y-auto scroll-fancy pr-1">{items.map((m, i) => { const sc = statusConfig[m.status] || statusConfig.new; return (<motion.div key={m.id} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: Math.min(i * 0.02, 0.3) }} className={cn("flex items-center gap-3 rounded-xl border bg-card p-3 cursor-pointer hover:shadow-sm transition-all", m.status === "new" ? "border-primary/30" : "border-border")} onClick={() => openMsg(m)}><div className={cn("grid place-items-center h-9 w-9 rounded-full font-bold text-xs shrink-0", m.status === "new" ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground")}>{m.name.slice(0, 1).toUpperCase()}</div><div className="flex-1 min-w-0"><div className="flex items-center gap-2"><span className={cn("text-sm truncate", m.status === "new" ? "font-bold text-ink" : "font-medium text-ink")}>{m.name}</span><Badge variant="secondary" className={cn("text-[0.6rem] shrink-0", sc.color)}>{sc.label}</Badge></div><div className="text-xs text-muted-foreground truncate">{m.subject}: {m.message.slice(0, 60)}</div></div><div className="text-[0.7rem] text-muted-foreground shrink-0 hidden sm:block">{new Date(m.createdAt).toLocaleDateString("es-BO", { day: "2-digit", month: "short" })}</div></motion.div>); })}</div>
      )}
      <AnimatePresence>{selected && (<motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-[70] bg-ink/60 backdrop-blur-sm flex items-stretch justify-center p-0 sm:p-6" onClick={() => setSelected(null)}><motion.div initial={{ y: 30, opacity: 0 }} animate={{ y: 0, opacity: 1 }} exit={{ y: 20, opacity: 0 }} transition={{ type: "spring", damping: 26, stiffness: 280 }} onClick={(e) => e.stopPropagation()} className="bg-background w-full sm:max-w-lg sm:rounded-2xl shadow-2xl flex flex-col max-h-screen sm:max-h-[85vh] overflow-hidden"><div className="flex items-center justify-between px-5 py-4 border-b border-border shrink-0"><div className="flex items-center gap-3 min-w-0"><div className="grid place-items-center h-10 w-10 rounded-full bg-primary text-primary-foreground font-bold shrink-0">{selected.name.slice(0, 1).toUpperCase()}</div><div className="min-w-0"><h3 className="font-display font-bold text-ink truncate">{selected.name}</h3><a href={`mailto:${selected.email}`} className="text-xs text-primary hover:underline truncate block">{selected.email}</a></div></div><Button variant="ghost" size="icon" onClick={() => setSelected(null)}><X className="h-5 w-5" /></Button></div><div className="flex-1 overflow-y-auto scroll-fancy px-5 py-4"><div className="flex items-center gap-2 mb-3"><Badge variant="secondary" className="text-[0.65rem]">{selected.subject}</Badge><span className="text-xs text-muted-foreground">{new Date(selected.createdAt).toLocaleString("es-BO")}</span></div><p className="text-sm text-foreground/90 whitespace-pre-wrap leading-relaxed">{selected.message}</p></div><div className="flex items-center gap-2 px-5 py-4 border-t border-border bg-muted/30 shrink-0"><Button asChild size="sm" className="bg-primary hover:bg-primary/90 text-primary-foreground"><a href={`mailto:${selected.email}?subject=Re: ${encodeURIComponent(selected.subject)}`}><Mail className="h-4 w-4 mr-1.5" />Responder</a></Button><Button variant="secondary" size="sm" onClick={() => updateStatus(selected.id, "replied")}><MailOpen className="h-4 w-4 mr-1.5" />Marcar respondido</Button><Button variant="ghost" size="sm" onClick={() => updateStatus(selected.id, "archived")}><Archive className="h-4 w-4 mr-1.5" />Archivar</Button><Button variant="ghost" size="sm" className="ml-auto text-destructive hover:text-destructive" onClick={() => remove(selected.id)}><Trash2 className="h-4 w-4" /></Button></div></motion.div></motion.div>)}</AnimatePresence>
    </div>
  );
}
